"""
Dynamic code quality tests generated by CruiseMode TestGenerationAgent.
Tests are grounded in actual code scanned from the sandbox.
"""

import os
import sys

SANDBOX = os.path.abspath(".sandbox")
sys.path.insert(0, SANDBOX)


class TestCodeQuality:
    """Tests generated from real code analysis of the sandbox."""

    def test_service_syntax(self):
        """Verify service.py is valid Python syntax."""
        import py_compile
        py_compile.compile(os.path.join(SANDBOX, "service.py"), doraise=True)

    def test_models_syntax(self):
        """Verify models.py is valid Python syntax."""
        import py_compile
        py_compile.compile(os.path.join(SANDBOX, "models.py"), doraise=True)

