"""
API tests for the Refund API endpoint.
Generated by CruiseMode TestGenerationAgent.
Tests run against the sandbox copy at: .sandbox/
"""

import sys
import os

# Add sandbox to path so we import the patched version
sys.path.insert(0, os.path.abspath(".sandbox"))

from fastapi.testclient import TestClient
from app import app


client = TestClient(app)


class TestRefundAPI:
    """API tests covering all HTTP status code scenarios."""

    def test_successful_refund(self):
        """POST /refund with valid data should return 200."""
        response = client.post("/refund", json={
            "payment_id": "PAY-100",
            "payment_status": "completed",
            "amount": 99.99,
            "customer_email": "customer@example.com",
            "card_number": "4111111111111111",
        })
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "success"
        assert data["amount"] == 99.99
        assert "refund_id" in data

    def test_invalid_amount_returns_400(self):
        """POST /refund with zero amount should return 400."""
        response = client.post("/refund", json={
            "payment_id": "PAY-101",
            "payment_status": "completed",
            "amount": 0,
            "customer_email": "customer@example.com",
            "card_number": "4111111111111111",
        })
        assert response.status_code == 400

    def test_pending_payment_returns_409(self):
        """AC-003: POST /refund with pending payment should return 409."""
        response = client.post("/refund", json={
            "payment_id": "PAY-102",
            "payment_status": "pending",
            "amount": 50.00,
            "customer_email": "customer@example.com",
            "card_number": "4111111111111111",
        })
        assert response.status_code == 409


class TestPIISafety:
    """AC-004: Sensitive data must not be exposed in responses."""

    def test_card_number_not_in_response(self):
        """Response body should not contain the card number."""
        response = client.post("/refund", json={
            "payment_id": "PAY-200",
            "payment_status": "completed",
            "amount": 10.00,
            "customer_email": "secret@example.com",
            "card_number": "4111111111111111",
        })
        assert response.status_code == 200
        body = response.text
        assert "4111111111111111" not in body
        assert "secret@example.com" not in body
