"""
Unit tests for refund validation logic.
Generated by CruiseMode TestGenerationAgent.
Tests run against the sandbox copy at: .sandbox/
"""

import sys
import os
import uuid

# Add sandbox to path so we import the patched version
sys.path.insert(0, os.path.abspath(".sandbox"))

from models import RefundRequest, PaymentStatus
from refund_service import process_refund


class TestRefundAmountValidation:
    """AC-001: Refund amount must be greater than zero."""

    def test_valid_refund_amount(self):
        """Refund with positive amount should succeed."""
        request = RefundRequest(
            payment_id="PAY-001",
            payment_status=PaymentStatus.COMPLETED,
            amount=50.00,
            customer_email="test@example.com",
            card_number="4111111111111111",
        )
        result = process_refund(request)
        assert result["status"] == "success"
        assert result["amount"] == 50.00

    def test_zero_refund_amount_rejected(self):
        """Refund with zero amount should return error."""
        request = RefundRequest(
            payment_id="PAY-002",
            payment_status=PaymentStatus.COMPLETED,
            amount=0,
            customer_email="test@example.com",
            card_number="4111111111111111",
        )
        result = process_refund(request)
        assert result["status"] == "error"
        assert result["code"] == 400

    def test_negative_refund_amount_rejected(self):
        """Refund with negative amount should return error."""
        request = RefundRequest(
            payment_id="PAY-003",
            payment_status=PaymentStatus.COMPLETED,
            amount=-10.00,
            customer_email="test@example.com",
            card_number="4111111111111111",
        )
        result = process_refund(request)
        assert result["status"] == "error"
        assert result["code"] == 400


class TestPaymentStatusValidation:
    """AC-002 & AC-003: Payment status requirements."""

    def test_completed_payment_allowed(self):
        """Completed payments should be refundable."""
        request = RefundRequest(
            payment_id="PAY-004",
            payment_status=PaymentStatus.COMPLETED,
            amount=25.00,
            customer_email="test@example.com",
            card_number="4111111111111111",
        )
        result = process_refund(request)
        assert result["status"] == "success"

    def test_pending_payment_returns_conflict(self):
        """AC-003: Pending payments must return conflict status."""
        request = RefundRequest(
            payment_id="PAY-005",
            payment_status=PaymentStatus.PENDING,
            amount=25.00,
            customer_email="test@example.com",
            card_number="4111111111111111",
        )
        result = process_refund(request)
        assert result["status"] == "conflict"
        assert result["code"] == 409
